import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//import lib bootstrap và global.css cho toàn dự án
import "bootstrap/dist/css/bootstrap.min.css";
//import bootstrap.min.js qua BootstrapClient.tsx để tránh lỗi "window is not defined"
import BootstrapClient from '@/components/BootstrapClient';
import "./globals.css";

//import fontAwesome Nextjs toàn cục cho dự án
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
