import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//import lib bootstrap vao layout tong cuc
import "bootstrap/dist/css/bootstrap.min.css";
//import BootstrapClient su dung bootstrap.bundle.min.js
import BootstrapClient from "@/components/BootstrapClient";

//import global.css
import "./globals.css";

//import fontAwesome vaof nextjs
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

//import modal context dung cho global toan du an
import ToastProvider from "@/contexts/ToastContext";
import { ModalProvider } from "@/contexts/ModalContext";
import BackToTop from "@/components/client/BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider>
          <ModalProvider>{children}</ModalProvider>
          <BackToTop></BackToTop>
        </ToastProvider>
      </body>
    </html>
  );
}
